/**
 * Flat role-permissions map (frontend source of truth).
 * Edit true/false directly inside each role object below.
 */

export const ROLE_MANAGEMENT_MOCK = {
  admin: {
    nav_dashboard: true,
    nav_become_expert: false,
    nav_categories: true,
    nav_experts: true,
    nav_users: true,
    nav_companies: true,
    nav_services: false,
    nav_jobs: true,
    nav_equipments: true,
    nav_role_management: true,
    nav_pricing: true,
    nav_enquiries: true,

    dashboard_registered_companies: true,
    dashboard_total_users: true,
    dashboard_total_experts: true,
    dashboard_active_jobs: true,
    dashboard_analytics_overview: true,

    dashboard_view: true,
    users_view: true,
    users_add: true,
    users_edit: true,
    users_delete: true,
    users_approve: true,
    experts_view: true,
    experts_add: true,
    experts_edit: true,
    experts_delete: true,
    experts_approve: true,
    company_view: true,
    company_add: true,
    company_edit: true,
    company_delete: true,
    company_approve: true,
    services_view: false,
    services_add: false,
    services_edit: false,
    services_delete: false,
    jobs_view: true,
    jobs_add: true,
    jobs_edit: true,
    jobs_delete: true,
    jobs_apply: true,
    jobs_approve: true,
    equipments_view: true,
    equipments_add: true,
    equipments_edit: true,
    equipments_delete: true,
    categories_view: true,
    categories_add: true,
    categories_edit: true,
    categories_delete: true,
    categories_view_sub_category: true,
    categories_add_sub_category: true,
    categories_edit_sub_category: true,
    categories_delete_sub_category: true,
    role_management_view: true,
    role_management_add: true,
    role_management_edit: true,
    role_management_delete: true,
    pricing_view: true,
    pricing_edit: true,

    enquiries_view: true,
    enquiries_delete: true,
    enquiries_respond: true,
  },
  user: {
    nav_dashboard: true,
    nav_become_expert: true,
    nav_categories: false,
    nav_experts: false,
    nav_users: false,
    nav_companies: false,
    nav_services: false,
    nav_jobs: false,
    nav_equipments: false,
    nav_role_management: false,
    nav_pricing: false,
    nav_enquiries: true,

    dashboard_registered_companies: false,
    dashboard_total_users: false,
    dashboard_total_experts: false,
    dashboard_active_jobs: false,
    dashboard_analytics_overview: false,

    dashboard_view: true,
    users_view: true,
    users_add: true,
    users_edit: true,
    users_delete: true,
    users_approve: true,
    experts_view: true,
    experts_add: true,
    experts_edit: true,
    experts_delete: true,
    experts_approve: true,
    company_view: true,
    company_add: true,
    company_edit: true,
    company_delete: true,
    company_approve: true,
    services_view: false,
    services_add: false,
    services_edit: false,
    services_delete: false,
    jobs_view: true,
    jobs_add: true,
    jobs_edit: true,
    jobs_delete: true,
    jobs_apply: true,
    jobs_approve: true,
    equipments_view: true,
    equipments_add: true,
    equipments_edit: true,
    equipments_delete: true,
    categories_view: true,
    categories_add: false,
    categories_edit: false,
    categories_delete: false,
    categories_view_sub_category: true,
    categories_add_sub_category: false,
    categories_edit_sub_category: false,
    categories_delete_sub_category: false,
    role_management_view: false,
    role_management_add: false,
    role_management_edit: false,
    role_management_delete: false,
    pricing_view: false,
    pricing_edit: false,

    enquiries_view: true,
    enquiries_delete: true,
    enquiries_respond: true,
  },
  expert: {
    nav_dashboard: true,
    nav_become_expert: false,
    nav_categories: true,
    nav_experts: true,
    nav_users: true,
    nav_companies: true,
    nav_services: false,
    nav_jobs: true,
    nav_equipments: true,
    nav_role_management: true,
    nav_pricing: false,
    nav_enquiries: true,

    dashboard_registered_companies: true,
    dashboard_total_users: true,
    dashboard_total_experts: true,
    dashboard_active_jobs: true,
    dashboard_analytics_overview: false,

    dashboard_view: true,
    users_view: true,
    users_add: true,
    users_edit: true,
    users_delete: true,
    users_approve: true,
    experts_view: true,
    experts_add: true,
    experts_edit: true,
    experts_delete: true,
    experts_approve: true,
    company_view: true,
    company_add: true,
    company_edit: true,
    company_delete: true,
    company_approve: true,
    services_view: false,
    services_add: false,
    services_edit: false,
    services_delete: false,
    jobs_view: true,
    jobs_add: true,
    jobs_edit: true,
    jobs_delete: true,
    jobs_apply: true,
    jobs_approve: true,
    equipments_view: true,
    equipments_add: true,
    equipments_edit: true,
    equipments_delete: true,
    categories_view: true,
    categories_add: true,
    categories_edit: true,
    categories_delete: true,
    categories_view_sub_category: true,
    categories_add_sub_category: true,
    categories_edit_sub_category: true,
    categories_delete_sub_category: true,
    role_management_view: false,
    role_management_add: false,
    role_management_edit: false,
    role_management_delete: false,
    pricing_view: false,
    pricing_edit: false,

    enquiries_view: true,
    enquiries_delete: true,
    enquiries_respond: true,
  },
  company: {
    nav_dashboard: true,
    nav_become_expert: false,
    nav_categories: true,
    nav_experts: true,
    nav_users: true,
    nav_companies: true,
    nav_services: true,
    nav_jobs: true,
    nav_equipments: true,
    nav_role_management: false,
    nav_pricing: false,
    nav_enquiries: true,

    dashboard_registered_companies: true,
    dashboard_total_users: true,
    dashboard_total_experts: true,
    dashboard_active_jobs: true,
    dashboard_analytics_overview: false,

    dashboard_view: true,
    users_view: true,
    users_add: false,
    users_edit: false,
    users_delete: false,
    users_approve: true,
    experts_view: true,
    experts_add: true,
    experts_edit: false,
    experts_delete: false,
    experts_approve: true,
    company_view: true,
    company_add: false,
    company_edit: false,
    company_delete: false,
    company_approve: false,
    services_view: true,
    services_add: true,
    services_edit: true,
    services_delete: true,
    jobs_view: true,
    jobs_add: true,
    jobs_edit: true,
    jobs_delete: true,
    jobs_apply: true,
    jobs_approve: true,
    equipments_view: true,
    equipments_add: true,
    equipments_edit: true,
    equipments_delete: true,
    categories_view: true,
    categories_add: true,
    categories_edit: false,
    categories_delete: false,
    categories_view_sub_category: true,
    categories_add_sub_category: true,
    categories_edit_sub_category: false,
    categories_delete_sub_category: false,
    role_management_view: false,
    role_management_add: false,
    role_management_edit: false,
    role_management_delete: false,
    pricing_view: false,
    pricing_edit: false,

    enquiries_view: true,
    enquiries_delete: true,
    enquiries_respond: true,
  },
};

export function normalizeRoleKey(roleKey) {
  const key = String(roleKey || "").toLowerCase();
  if (key && ROLE_MANAGEMENT_MOCK[key]) return key;
  return "admin";
}

export function getRolePermissionObject(roleKey) {
  return ROLE_MANAGEMENT_MOCK[normalizeRoleKey(roleKey)];
}
