import { Barlow, Quicksand } from "next/font/google";
import { AuthProvider } from "@/utilities/AuthContext";
import "@/styles/global.scss";

export const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Nipunah",
  description: "Generated by Nipunah",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${quicksand.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
