/**
 * Public Jobs browse — mock listings aligned with Post a Job form fields.
 */

export const PUBLIC_JOBS_MOCK = [
  {
    id: 101,
    jobId: "PUB-JOB-101",
    title: "Senior Software Engineer - Java Technologies",
    postedBy: {
      companyId: 11,
      companyName: "Siemens",
      companyShortName: "SIEMENS",
    },
    companyRating: 4.0,
    companyReviews: 5970,
    experienceRequired: "2-5 years",
    salaryNotDisclosed: false,
    salaryRange: { min: "12 LPA", max: "18 LPA" },
    location: {
      city: "Pune",
      state: "Maharashtra",
      pinCode: "411001",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Full Time",
    employmentNature: "Permanent",
    workMode: "Hybrid",
    openings: 3,
    qualifications:
      "Bachelor's or Master's degree in Computer Science or related field.",
    description:
      "<p>5 - 8 years of experience in Software Engineering in an Agile Environment, with strong Java, Spring Boot and microservices skills.</p>",
    keyResponsibilities:
      "<ul><li>Design and develop Java applications</li><li>Collaborate in Agile squads</li><li>Mentor junior engineers</li></ul>",
    requiredSkills:
      "<ul><li>Agile</li><li>Java</li><li>Asynchronous</li><li>Architecture</li><li>Debugging</li><li>Junit</li><li>React</li><li>Angular</li></ul>",
    skillTags: [
      "Agile",
      "Java",
      "Asynchronous",
      "Architecture",
      "Debugging",
      "Junit",
      "React",
      "Angular",
    ],
    preferredSkillTags: ["Agile"],
    weOffer:
      "<ul><li>Health Insurance</li><li>Performance Bonus</li><li>Paid Leave</li><li>Training</li></ul>",
    jobPostedDate: "2026-07-28",
    applicationDeadline: "2026-09-15",
    isActive: true,
    status: "approved",
    alreadyApplied: true,
    createdOn: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 102,
    jobId: "PUB-JOB-102",
    title: "Hiring: ServiceNow Professionals Multiple Modules",
    postedBy: {
      companyId: 1,
      companyName: "eLabs Infotech",
      companyShortName: "eLabs",
    },
    companyRating: 3.8,
    companyReviews: 420,
    experienceRequired: "5-10 years",
    salaryNotDisclosed: true,
    salaryRange: { min: "Not Disclosed", max: "Not Disclosed" },
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      pinCode: "560066",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Full Time",
    employmentNature: "Permanent",
    workMode: "Hybrid",
    openings: 5,
    qualifications:
      "Bachelor's or Master's in CS, IT, Engineering or related field.",
    description:
      "<p>We are looking for ServiceNow professionals with strong implementation and integration experience across multiple modules.</p>",
    keyResponsibilities:
      "<ul><li>Design ServiceNow solutions</li><li>Build workflows and integrations</li></ul>",
    requiredSkills:
      "<ul><li>ServiceNow</li><li>JavaScript</li><li>ITSM</li><li>Flow Designer</li><li>REST APIs</li></ul>",
    skillTags: ["ServiceNow", "JavaScript", "ITSM", "Flow Designer", "REST APIs"],
    weOffer:
      "<ul><li>Insurance</li><li>Bonus</li><li>Training & Certifications</li></ul>",
    jobPostedDate: "2026-07-20",
    applicationDeadline: "2026-08-30",
    isActive: true,
    status: "approved",
    createdOn: Date.now() - 6 * 24 * 60 * 60 * 1000,
  },
  {
    id: 103,
    jobId: "PUB-JOB-103",
    title: "Frontend Developer",
    postedBy: {
      companyId: 2,
      companyName: "Global Logistics Inc",
      companyShortName: "GLI",
    },
    companyRating: 4.2,
    companyReviews: 890,
    experienceRequired: "2-5 years",
    salaryNotDisclosed: false,
    salaryRange: { min: "10 LPA", max: "15 LPA" },
    location: {
      city: "Miami",
      state: "Florida",
      pinCode: "33101",
      countryCode: "US",
      country: "United States",
    },
    employmentType: "Contract",
    employmentNature: "Contractual",
    workMode: "Remote",
    openings: 1,
    qualifications: "Any Graduate in IT or related field.",
    description:
      "<p>React and JavaScript development for logistics platforms with a focus on responsive UI.</p>",
    keyResponsibilities:
      "<ul><li>Implement UI features</li><li>Ensure responsive design</li></ul>",
    requiredSkills:
      "<ul><li>React</li><li>JavaScript</li><li>CSS</li><li>HTML</li><li>Redux</li></ul>",
    skillTags: ["React", "JavaScript", "CSS", "HTML", "Redux"],
    weOffer:
      "<ul><li>Transportation Allowance</li><li>Food Coupons</li><li>Paid Leave</li></ul>",
    jobPostedDate: "2026-07-22",
    applicationDeadline: "2026-08-20",
    isActive: true,
    status: "approved",
    alreadyApplied: true,
    createdOn: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: 104,
    jobId: "PUB-JOB-104",
    title: "Marine Field Engineer",
    postedBy: {
      companyId: 5,
      companyName: "OceanTech Marine",
      companyShortName: "OTM",
    },
    companyRating: 4.1,
    companyReviews: 210,
    experienceRequired: "5-10 years",
    salaryNotDisclosed: false,
    salaryRange: { min: "Competitive", max: "Competitive" },
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      pinCode: "600001",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Full Time",
    employmentNature: "Permanent",
    workMode: "Onboard Vessel",
    openings: 2,
    qualifications: "Marine Engineering degree preferred.",
    description:
      "<p>Onboard vessel engineering support for commercial fleet operations across Asian routes.</p>",
    keyResponsibilities:
      "<ul><li>Onboard maintenance</li><li>Safety compliance</li><li>Crew coordination</li></ul>",
    requiredSkills:
      "<ul><li>Marine Engineering</li><li>Safety</li><li>Troubleshooting</li><li>Leadership</li></ul>",
    skillTags: ["Marine Engineering", "Safety", "Troubleshooting", "Leadership"],
    weOffer:
      "<ul><li>Accommodation</li><li>Food</li><li>Insurance</li><li>Paid Leave</li></ul>",
    jobPostedDate: "2026-07-25",
    applicationDeadline: "2026-09-01",
    isActive: true,
    status: "approved",
    createdOn: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 105,
    jobId: "PUB-JOB-105",
    title: "DevOps Trainee",
    postedBy: {
      companyId: 8,
      companyName: "CloudNest Systems",
      companyShortName: "CNS",
    },
    companyRating: 3.9,
    companyReviews: 156,
    experienceRequired: "0-2 years",
    salaryNotDisclosed: false,
    salaryRange: { min: "4 LPA", max: "6 LPA" },
    location: {
      city: "Hyderabad",
      state: "Telangana",
      pinCode: "500081",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Trainee",
    employmentNature: "Temporary",
    workMode: "Office",
    openings: 4,
    qualifications: "B.Tech / B.E. in Computer Science or IT.",
    description:
      "<p>Entry-level DevOps role with hands-on CI/CD, containers and cloud fundamentals training.</p>",
    keyResponsibilities:
      "<ul><li>Assist CI/CD pipelines</li><li>Monitor deployments</li><li>Learn cloud ops</li></ul>",
    requiredSkills:
      "<ul><li>Linux</li><li>Git</li><li>Docker</li><li>CI/CD</li><li>AWS Basics</li></ul>",
    skillTags: ["Linux", "Git", "Docker", "CI/CD", "AWS Basics"],
    weOffer:
      "<ul><li>Training</li><li>Mentorship</li><li>Health Insurance</li></ul>",
    jobPostedDate: "2026-07-27",
    applicationDeadline: "2026-08-25",
    isActive: true,
    status: "approved",
    createdOn: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 106,
    jobId: "PUB-JOB-106",
    title: "Offshore Project Coordinator",
    postedBy: {
      companyId: 9,
      companyName: "PetroServe Global",
      companyShortName: "PSG",
    },
    companyRating: 4.3,
    companyReviews: 1120,
    experienceRequired: "10+ years",
    salaryNotDisclosed: false,
    salaryRange: { min: "25 LPA", max: "35 LPA" },
    location: {
      city: "Abu Dhabi",
      state: "",
      pinCode: "",
      countryCode: "AE",
      country: "United Arab Emirates",
    },
    employmentType: "Rotation",
    employmentNature: "Permanent",
    workMode: "Offshore",
    openings: 1,
    qualifications: "Engineering degree with offshore project experience.",
    description:
      "<p>Coordinate offshore project delivery, vendor management and site readiness for energy projects.</p>",
    keyResponsibilities:
      "<ul><li>Project coordination</li><li>Vendor management</li><li>Site readiness</li></ul>",
    requiredSkills:
      "<ul><li>Project Management</li><li>Offshore Ops</li><li>HSE</li><li>Stakeholder Mgmt</li></ul>",
    skillTags: [
      "Project Management",
      "Offshore Ops",
      "HSE",
      "Stakeholder Mgmt",
    ],
    weOffer:
      "<ul><li>Accommodation</li><li>Transportation</li><li>Insurance</li><li>Bonus</li></ul>",
    jobPostedDate: "2026-07-18",
    applicationDeadline: "2026-09-10",
    isActive: true,
    status: "approved",
    createdOn: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
  {
    id: 107,
    jobId: "PUB-JOB-107",
    title: "Data Migration - Solution Consultant",
    postedBy: {
      companyId: 11,
      companyName: "Siemens",
      companyShortName: "SIEMENS",
    },
    companyRating: 4.0,
    companyReviews: 5970,
    experienceRequired: "2-5 years",
    salaryNotDisclosed: true,
    salaryRange: { min: "Not Disclosed", max: "Not Disclosed" },
    location: {
      city: "Pune",
      state: "Maharashtra",
      pinCode: "411001",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Full Time",
    employmentNature: "Permanent",
    workMode: "Hybrid",
    openings: 2,
    qualifications: "Bachelor's in Computer Science or related field.",
    description:
      "<p>Lead data migration solutions for enterprise clients with strong consulting and technical delivery skills.</p>",
    keyResponsibilities:
      "<ul><li>Solution consulting</li><li>Data migration design</li><li>Client workshops</li></ul>",
    requiredSkills:
      "<ul><li>Data Migration</li><li>Consulting</li><li>SQL</li><li>ETL</li></ul>",
    skillTags: ["Data Migration", "Consulting", "SQL", "ETL", "Agile"],
    preferredSkillTags: ["Agile"],
    weOffer:
      "<ul><li>Insurance</li><li>Bonus</li><li>Training</li></ul>",
    jobPostedDate: "2026-07-28",
    applicationDeadline: "2026-09-20",
    isActive: true,
    status: "approved",
    alreadyApplied: true,
    createdOn: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 108,
    jobId: "PUB-JOB-108",
    title: "Java Full Stack Developer",
    postedBy: {
      companyId: 11,
      companyName: "Siemens",
      companyShortName: "SIEMENS",
    },
    companyRating: 4.0,
    companyReviews: 5970,
    experienceRequired: "5-10 years",
    salaryNotDisclosed: false,
    salaryRange: { min: "15 LPA", max: "22 LPA" },
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      pinCode: "560001",
      countryCode: "IN",
      country: "India",
    },
    employmentType: "Full Time",
    employmentNature: "Permanent",
    workMode: "Office",
    openings: 4,
    qualifications: "B.Tech / M.Tech in CS or related.",
    description:
      "<p>Build scalable full-stack Java applications with modern frontend frameworks.</p>",
    keyResponsibilities:
      "<ul><li>Full stack development</li><li>Code reviews</li><li>Performance tuning</li></ul>",
    requiredSkills:
      "<ul><li>Java</li><li>Spring Boot</li><li>React</li><li>Microservices</li></ul>",
    skillTags: ["Java", "Spring Boot", "React", "Microservices", "Agile"],
    preferredSkillTags: ["Agile"],
    weOffer:
      "<ul><li>Health Insurance</li><li>Paid Leave</li><li>Training</li></ul>",
    jobPostedDate: "2026-07-26",
    applicationDeadline: "2026-09-05",
    isActive: true,
    status: "approved",
    createdOn: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
];
